// Code generated by 'go generate'; DO NOT EDIT.

package powerreport

import (
	"syscall"
	"unsafe"

	"golang.org/x/sys/windows"
)

var _ unsafe.Pointer

// Do the interface allocations only once for common
// Errno values.
const (
	errnoERROR_IO_PENDING = 997
)

var (
	errERROR_IO_PENDING error = syscall.Errno(errnoERROR_IO_PENDING)
	errERROR_EINVAL     error = syscall.EINVAL
)

// errnoErr returns common boxed Errno values, to prevent
// allocations at runtime.
func errnoErr(e syscall.Errno) error {
	switch e {
	case 0:
		return errERROR_EINVAL
	case errnoERROR_IO_PENDING:
		return errERROR_IO_PENDING
	}
	// TODO: add more here, after collecting data on the common
	// error values see on Windows. (perhaps when running
	// all.bat?)
	return e
}

var (
	modapi_ms_win_core_realtime_l1_1_1 = windows.NewLazySystemDLL("api-ms-win-core-realtime-l1-1-1.dll")
	modkernel32                        = windows.NewLazySystemDLL("kernel32.dll")

	procQueryInterruptTime         = modapi_ms_win_core_realtime_l1_1_1.NewProc("QueryInterruptTime")
	procGetProcessIoCounters       = modkernel32.NewProc("GetProcessIoCounters")
	procQueryUnbiasedInterruptTime = modkernel32.NewProc("QueryUnbiasedInterruptTime")
)

func queryInterruptTime(interruptTime *uint64) {
	syscall.SyscallN(procQueryInterruptTime.Addr(), uintptr(unsafe.Pointer(interruptTime)))
	return
}

func getProcessIoCounters(process windows.Handle, ioCounters *processIOCounters) (err error) {
	r1, _, e1 := syscall.SyscallN(procGetProcessIoCounters.Addr(), uintptr(process), uintptr(unsafe.Pointer(ioCounters)))
	if r1 == 0 {
		err = errnoErr(e1)
	}
	return
}

func queryUnbiasedInterruptTime(unbiasedTime *uint64) (err error) {
	r1, _, e1 := syscall.SyscallN(procQueryUnbiasedInterruptTime.Addr(), uintptr(unsafe.Pointer(unbiasedTime)))
	if r1 == 0 {
		err = errnoErr(e1)
	}
	return
}
