linters:
  disable-all: true
  enable:
    - gofumpt
    - govet
    - gci
    - staticcheck
    - paralleltest
    - ineffassign

linters-settings:
  gci:
    custom-order: true
    sections:
      - standard
      - prefix(github.com/sagernet/)
      - default
  staticcheck:
    checks:
      - all
      - -SA1003

run:
  go: "1.24"
  build-tags:
    - with_gvisor
    - with_quic
    - with_dhcp
    - with_wireguard
    - with_utls
    - with_reality_server
    - with_acme
    - with_clash_api

issues:
  exclude-dirs:
    - transport/simple-obfs
