// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: cybertom.proto

package cybertom

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CyberTom_UpdateUser_FullMethodName = "/proto.CyberTom/UpdateUser"
)

// CyberTomClient is the client API for CyberTom service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CyberTomClient interface {
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserReply, error)
}

type cyberTomClient struct {
	cc grpc.ClientConnInterface
}

func NewCyberTomClient(cc grpc.ClientConnInterface) CyberTomClient {
	return &cyberTomClient{cc}
}

func (c *cyberTomClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUserReply)
	err := c.cc.Invoke(ctx, CyberTom_UpdateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CyberTomServer is the server API for CyberTom service.
// All implementations must embed UnimplementedCyberTomServer
// for forward compatibility.
type CyberTomServer interface {
	UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserReply, error)
	mustEmbedUnimplementedCyberTomServer()
}

// UnimplementedCyberTomServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCyberTomServer struct{}

func (UnimplementedCyberTomServer) UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}
func (UnimplementedCyberTomServer) mustEmbedUnimplementedCyberTomServer() {}
func (UnimplementedCyberTomServer) testEmbeddedByValue()                  {}

// UnsafeCyberTomServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CyberTomServer will
// result in compilation errors.
type UnsafeCyberTomServer interface {
	mustEmbedUnimplementedCyberTomServer()
}

func RegisterCyberTomServer(s grpc.ServiceRegistrar, srv CyberTomServer) {
	// If the following call pancis, it indicates UnimplementedCyberTomServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CyberTom_ServiceDesc, srv)
}

func _CyberTom_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CyberTomServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CyberTom_UpdateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CyberTomServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CyberTom_ServiceDesc is the grpc.ServiceDesc for CyberTom service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CyberTom_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.CyberTom",
	HandlerType: (*CyberTomServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateUser",
			Handler:    _CyberTom_UpdateUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cybertom.proto",
}
