// Code generated by 'make update_certificates'. DO NOT EDIT.

package certificate

import (
	"crypto/x509"
	_ "embed"
)

//go:embed chrome.pem
var chromeIncludedPEM string

var chromeIncluded *x509.CertPool

func init() {
	chromeIncluded = x509.NewCertPool()
	chromeIncluded.AppendCertsFromPEM([]byte(chromeIncludedPEM))
}
