// Code generated by 'make update_certificates'. DO NOT EDIT.

package certificate

import (
	"crypto/x509"
	_ "embed"
)

//go:embed mozilla.pem
var mozillaIncludedPEM string

var mozillaIncluded *x509.CertPool

func init() {
	mozillaIncluded = x509.NewCertPool()
	mozillaIncluded.AppendCertsFromPEM([]byte(mozillaIncludedPEM))
}
