// Code generated by 'go generate'; DO NOT EDIT.

package winhttp

import (
	"syscall"
	"unsafe"

	"golang.org/x/sys/windows"
)

var _ unsafe.Pointer

// Do the interface allocations only once for common
// Errno values.
const (
	errnoERROR_IO_PENDING = 997
)

var (
	errERROR_IO_PENDING error = syscall.Errno(errnoERROR_IO_PENDING)
	errERROR_EINVAL     error = syscall.EINVAL
)

// errnoErr returns common boxed Errno values, to prevent
// allocations at runtime.
func errnoErr(e syscall.Errno) error {
	switch e {
	case 0:
		return errERROR_EINVAL
	case errnoERROR_IO_PENDING:
		return errERROR_IO_PENDING
	}
	// TODO: add more here, after collecting data on the common
	// error values see on Windows. (perhaps when running
	// all.bat?)
	return e
}

var (
	modwinhttp = windows.NewLazySystemDLL("winhttp.dll")

	procWinHttpCloseHandle       = modwinhttp.NewProc("WinHttpCloseHandle")
	procWinHttpConnect           = modwinhttp.NewProc("WinHttpConnect")
	procWinHttpOpen              = modwinhttp.NewProc("WinHttpOpen")
	procWinHttpOpenRequest       = modwinhttp.NewProc("WinHttpOpenRequest")
	procWinHttpQueryHeaders      = modwinhttp.NewProc("WinHttpQueryHeaders")
	procWinHttpQueryOption       = modwinhttp.NewProc("WinHttpQueryOption")
	procWinHttpReadData          = modwinhttp.NewProc("WinHttpReadData")
	procWinHttpReceiveResponse   = modwinhttp.NewProc("WinHttpReceiveResponse")
	procWinHttpSendRequest       = modwinhttp.NewProc("WinHttpSendRequest")
	procWinHttpSetOption         = modwinhttp.NewProc("WinHttpSetOption")
	procWinHttpSetStatusCallback = modwinhttp.NewProc("WinHttpSetStatusCallback")
	procWinHttpSetTimeouts       = modwinhttp.NewProc("WinHttpSetTimeouts")
)

func winHTTPCloseHandle(handle Handle) (err error) {
	r1, _, e1 := syscall.SyscallN(procWinHttpCloseHandle.Addr(), uintptr(handle))
	if r1 == 0 {
		err = errnoErr(e1)
	}
	return
}

func winHTTPConnect(sessionHandle Handle, serverName *uint16, serverPort uint16, reserved uint32) (handle Handle, err error) {
	r0, _, e1 := syscall.SyscallN(procWinHttpConnect.Addr(), uintptr(sessionHandle), uintptr(unsafe.Pointer(serverName)), uintptr(serverPort), uintptr(reserved))
	handle = Handle(r0)
	if handle == 0 {
		err = errnoErr(e1)
	}
	return
}

func winHTTPOpen(userAgent *uint16, accessType uint32, proxy *uint16, proxyBypass *uint16, flags uint32) (sessionHandle Handle, err error) {
	r0, _, e1 := syscall.SyscallN(procWinHttpOpen.Addr(), uintptr(unsafe.Pointer(userAgent)), uintptr(accessType), uintptr(unsafe.Pointer(proxy)), uintptr(unsafe.Pointer(proxyBypass)), uintptr(flags))
	sessionHandle = Handle(r0)
	if sessionHandle == 0 {
		err = errnoErr(e1)
	}
	return
}

func winHTTPOpenRequest(connectHandle Handle, verb *uint16, objectName *uint16, version *uint16, referrer *uint16, acceptTypes **uint16, flags uint32) (requestHandle Handle, err error) {
	r0, _, e1 := syscall.SyscallN(procWinHttpOpenRequest.Addr(), uintptr(connectHandle), uintptr(unsafe.Pointer(verb)), uintptr(unsafe.Pointer(objectName)), uintptr(unsafe.Pointer(version)), uintptr(unsafe.Pointer(referrer)), uintptr(unsafe.Pointer(acceptTypes)), uintptr(flags))
	requestHandle = Handle(r0)
	if requestHandle == 0 {
		err = errnoErr(e1)
	}
	return
}

func winHTTPQueryHeaders(requestHandle Handle, infoLevel uint32, name *uint16, buffer unsafe.Pointer, bufferLen *uint32, index *uint32) (err error) {
	r1, _, e1 := syscall.SyscallN(procWinHttpQueryHeaders.Addr(), uintptr(requestHandle), uintptr(infoLevel), uintptr(unsafe.Pointer(name)), uintptr(buffer), uintptr(unsafe.Pointer(bufferLen)), uintptr(unsafe.Pointer(index)))
	if r1 == 0 {
		err = errnoErr(e1)
	}
	return
}

func winHTTPQueryOption(handle Handle, option uint32, buffer unsafe.Pointer, bufferLen *uint32) (err error) {
	r1, _, e1 := syscall.SyscallN(procWinHttpQueryOption.Addr(), uintptr(handle), uintptr(option), uintptr(buffer), uintptr(unsafe.Pointer(bufferLen)))
	if r1 == 0 {
		err = errnoErr(e1)
	}
	return
}

func winHTTPReadData(requestHandle Handle, buffer *byte, bufferSize uint32, bytesRead *uint32) (err error) {
	r1, _, e1 := syscall.SyscallN(procWinHttpReadData.Addr(), uintptr(requestHandle), uintptr(unsafe.Pointer(buffer)), uintptr(bufferSize), uintptr(unsafe.Pointer(bytesRead)))
	if r1 == 0 {
		err = errnoErr(e1)
	}
	return
}

func winHTTPReceiveResponse(requestHandle Handle, reserved uintptr) (err error) {
	r1, _, e1 := syscall.SyscallN(procWinHttpReceiveResponse.Addr(), uintptr(requestHandle), uintptr(reserved))
	if r1 == 0 {
		err = errnoErr(e1)
	}
	return
}

func winHTTPSendRequest(requestHandle Handle, headers *uint16, headersLength uint32, optional *byte, optionalLength uint32, totalLength uint32, context uintptr) (err error) {
	r1, _, e1 := syscall.SyscallN(procWinHttpSendRequest.Addr(), uintptr(requestHandle), uintptr(unsafe.Pointer(headers)), uintptr(headersLength), uintptr(unsafe.Pointer(optional)), uintptr(optionalLength), uintptr(totalLength), uintptr(context))
	if r1 == 0 {
		err = errnoErr(e1)
	}
	return
}

func winHTTPSetOption(handle Handle, option uint32, buffer unsafe.Pointer, bufferLen uint32) (err error) {
	r1, _, e1 := syscall.SyscallN(procWinHttpSetOption.Addr(), uintptr(handle), uintptr(option), uintptr(buffer), uintptr(bufferLen))
	if r1 == 0 {
		err = errnoErr(e1)
	}
	return
}

func winHTTPSetStatusCallback(handle Handle, callback uintptr, notificationFlags uint32, reserved uintptr) (previousCallback uintptr, err error) {
	r0, _, e1 := syscall.SyscallN(procWinHttpSetStatusCallback.Addr(), uintptr(handle), uintptr(callback), uintptr(notificationFlags), uintptr(reserved))
	previousCallback = uintptr(r0)
	if previousCallback == invalidStatusCallback {
		err = errnoErr(e1)
	}
	return
}

func winHTTPSetTimeouts(handle Handle, resolveTimeout int32, connectTimeout int32, sendTimeout int32, receiveTimeout int32) (err error) {
	r1, _, e1 := syscall.SyscallN(procWinHttpSetTimeouts.Addr(), uintptr(handle), uintptr(resolveTimeout), uintptr(connectTimeout), uintptr(sendTimeout), uintptr(receiveTimeout))
	if r1 == 0 {
		err = errnoErr(e1)
	}
	return
}
