name: Build_Self

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version name"
        required: true
        type: string
      build:
        description: "Build type"
        required: true
        type: choice
        default: "Binary"
        options:
          - Binary
  push:
    branches:
      - stable
      - testing
      - unstable

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}-${{ inputs.build }}
  cancel-in-progress: true

jobs:
  calculate_version:
    name: Calculate version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.outputs.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ~1.25.9
      - name: Check input version
        if: github.event_name == 'workflow_dispatch'
        run: |-
          echo "version=${{ inputs.version }}"
          echo "version=${{ inputs.version }}" >> "$GITHUB_ENV"
      - name: Calculate version
        if: github.event_name != 'workflow_dispatch'
        run: |-
          go run -v ./cmd/internal/read_tag --ci --nightly
      - name: Set outputs
        id: outputs
        run: |-
          echo "version=$version" >> "$GITHUB_OUTPUT"

  build_windows:
    name: Build Windows binaries
    if: github.event_name != 'workflow_dispatch' || inputs.build == 'Binary'
    runs-on: windows-latest
    needs:
      - calculate_version
    strategy:
      matrix:
        include:
          - { arch: amd64, naive: false }
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ^1.25.4
      - name: Set tag
        run: |-
          git ls-remote --exit-code --tags origin v${{ needs.calculate_version.outputs.version }} || echo "PUBLISHED=false" >> "$env:GITHUB_ENV"
          git tag v${{ needs.calculate_version.outputs.version }} -f
      - name: Build
        if: matrix.naive
        run: |
          $TAGS = Get-Content release/DEFAULT_BUILD_TAGS_WINDOWS
          $LDFLAGS_SHARED = Get-Content release/LDFLAGS
          mkdir -p dist
          go build -v -trimpath -o dist/sing-box.exe -tags "$TAGS" `
          -ldflags "-X 'github.com/sagernet/sing-box/constant.Version=${{ needs.calculate_version.outputs.version }}' $LDFLAGS_SHARED -s -w -buildid=" `
          ./cmd/sing-box
        env:
          CGO_ENABLED: "0"
          GOOS: windows
          GOARCH: ${{ matrix.arch }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        if: ${{ !matrix.naive }}
        run: |
          $TAGS = Get-Content release/DEFAULT_BUILD_TAGS_OTHERS
          $LDFLAGS_SHARED = Get-Content release/LDFLAGS
          mkdir -p dist
          go build -v -trimpath -o dist/sing-box.exe -tags "$TAGS" `
          -ldflags "-X 'github.com/sagernet/sing-box/constant.Version=${{ needs.calculate_version.outputs.version }}' $LDFLAGS_SHARED -s -w -buildid=" `
          ./cmd/sing-box
        env:
          CGO_ENABLED: "0"
          GOOS: windows
          GOARCH: ${{ matrix.arch }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract libcronet.dll
        if: matrix.naive
        run: |
          $CRONET_GO_VERSION = Get-Content .github/CRONET_GO_VERSION
          $env:CGO_ENABLED = "0"
          go run -v "github.com/sagernet/cronet-go/cmd/build-naive@$CRONET_GO_VERSION" extract-lib --target windows/${{ matrix.arch }} -o dist
      - name: Archive
        if: matrix.naive
        run: |
          $DIR_NAME = "sing-box-${{ needs.calculate_version.outputs.version }}-windows-${{ matrix.arch }}"
          mkdir "dist/$DIR_NAME"
          Copy-Item LICENSE "dist/$DIR_NAME"
          Copy-Item "dist/sing-box.exe" "dist/$DIR_NAME"
          Copy-Item "dist/libcronet.dll" "dist/$DIR_NAME"
          Compress-Archive -Path "dist/$DIR_NAME" -DestinationPath "dist/$DIR_NAME.zip"
          Remove-Item -Recurse "dist/$DIR_NAME"
      - name: Archive
        if: ${{ !matrix.naive }}
        run: |
          $DIR_NAME = "sing-box-${{ needs.calculate_version.outputs.version }}-windows-${{ matrix.arch }}"
          mkdir "dist/$DIR_NAME"
          Copy-Item LICENSE "dist/$DIR_NAME"
          Copy-Item "dist/sing-box.exe" "dist/$DIR_NAME"
          Compress-Archive -Path "dist/$DIR_NAME" -DestinationPath "dist/$DIR_NAME.zip"
          Remove-Item -Recurse "dist/$DIR_NAME"
      - name: Cleanup
        if: matrix.naive
        run: Remove-Item dist/sing-box.exe, dist/libcronet.dll
      - name: Cleanup
        if: ${{ !matrix.naive }}
        run: Remove-Item dist/sing-box.exe
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: binary-windows_${{ matrix.arch }}
          path: "dist"
